export type Country = { code: string; name: string; emoji: string };
export type Region  = { code: string; name: string };

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", emoji: "🇦🇫" },
  { code: "AL", name: "Albania", emoji: "🇦🇱" },
  { code: "DZ", name: "Algeria", emoji: "🇩🇿" },
  { code: "AD", name: "Andorra", emoji: "🇦🇩" },
  { code: "AO", name: "Angola", emoji: "🇦🇴" },
  { code: "AG", name: "Antigua and Barbuda", emoji: "🇦🇬" },
  { code: "AR", name: "Argentina", emoji: "🇦🇷" },
  { code: "AM", name: "Armenia", emoji: "🇦🇲" },
  { code: "AU", name: "Australia", emoji: "🇦🇺" },
  { code: "AT", name: "Austria", emoji: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", emoji: "🇦🇿" },
  { code: "BS", name: "Bahamas", emoji: "🇧🇸" },
  { code: "BH", name: "Bahrain", emoji: "🇧🇭" },
  { code: "BD", name: "Bangladesh", emoji: "🇧🇩" },
  { code: "BB", name: "Barbados", emoji: "🇧🇧" },
  { code: "BY", name: "Belarus", emoji: "🇧🇾" },
  { code: "BE", name: "Belgium", emoji: "🇧🇪" },
  { code: "BZ", name: "Belize", emoji: "🇧🇿" },
  { code: "BJ", name: "Benin", emoji: "🇧🇯" },
  { code: "BT", name: "Bhutan", emoji: "🇧🇹" },
  { code: "BO", name: "Bolivia", emoji: "🇧🇴" },
  { code: "BA", name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
  { code: "BW", name: "Botswana", emoji: "🇧🇼" },
  { code: "BR", name: "Brazil", emoji: "🇧🇷" },
  { code: "BN", name: "Brunei", emoji: "🇧🇳" },
  { code: "BG", name: "Bulgaria", emoji: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", emoji: "🇧🇫" },
  { code: "BI", name: "Burundi", emoji: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", emoji: "🇨🇻" },
  { code: "KH", name: "Cambodia", emoji: "🇰🇭" },
  { code: "CM", name: "Cameroon", emoji: "🇨🇲" },
  { code: "CA", name: "Canada", emoji: "🇨🇦" },
  { code: "CF", name: "Central African Republic", emoji: "🇨🇫" },
  { code: "TD", name: "Chad", emoji: "🇹🇩" },
  { code: "CL", name: "Chile", emoji: "🇨🇱" },
  { code: "CN", name: "China", emoji: "🇨🇳" },
  { code: "CO", name: "Colombia", emoji: "🇨🇴" },
  { code: "KM", name: "Comoros", emoji: "🇰🇲" },
  { code: "CG", name: "Congo", emoji: "🇨🇬" },
  { code: "CR", name: "Costa Rica", emoji: "🇨🇷" },
  { code: "HR", name: "Croatia", emoji: "🇭🇷" },
  { code: "CU", name: "Cuba", emoji: "🇨🇺" },
  { code: "CY", name: "Cyprus", emoji: "🇨🇾" },
  { code: "CZ", name: "Czech Republic", emoji: "🇨🇿" },
  { code: "DK", name: "Denmark", emoji: "🇩🇰" },
  { code: "DJ", name: "Djibouti", emoji: "🇩🇯" },
  { code: "DM", name: "Dominica", emoji: "🇩🇲" },
  { code: "DO", name: "Dominican Republic", emoji: "🇩🇴" },
  { code: "EC", name: "Ecuador", emoji: "🇪🇨" },
  { code: "EG", name: "Egypt", emoji: "🇪🇬" },
  { code: "SV", name: "El Salvador", emoji: "🇸🇻" },
  { code: "GQ", name: "Equatorial Guinea", emoji: "🇬🇶" },
  { code: "ER", name: "Eritrea", emoji: "🇪🇷" },
  { code: "EE", name: "Estonia", emoji: "🇪🇪" },
  { code: "SZ", name: "Eswatini", emoji: "🇸🇿" },
  { code: "ET", name: "Ethiopia", emoji: "🇪🇹" },
  { code: "FJ", name: "Fiji", emoji: "🇫🇯" },
  { code: "FI", name: "Finland", emoji: "🇫🇮" },
  { code: "FR", name: "France", emoji: "🇫🇷" },
  { code: "GA", name: "Gabon", emoji: "🇬🇦" },
  { code: "GM", name: "Gambia", emoji: "🇬🇲" },
  { code: "GE", name: "Georgia", emoji: "🇬🇪" },
  { code: "DE", name: "Germany", emoji: "🇩🇪" },
  { code: "GH", name: "Ghana", emoji: "🇬🇭" },
  { code: "GR", name: "Greece", emoji: "🇬🇷" },
  { code: "GD", name: "Grenada", emoji: "🇬🇩" },
  { code: "GT", name: "Guatemala", emoji: "🇬🇹" },
  { code: "GN", name: "Guinea", emoji: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", emoji: "🇬🇼" },
  { code: "GY", name: "Guyana", emoji: "🇬🇾" },
  { code: "HT", name: "Haiti", emoji: "🇭🇹" },
  { code: "HN", name: "Honduras", emoji: "🇭🇳" },
  { code: "HU", name: "Hungary", emoji: "🇭🇺" },
  { code: "IS", name: "Iceland", emoji: "🇮🇸" },
  { code: "IN", name: "India", emoji: "🇮🇳" },
  { code: "ID", name: "Indonesia", emoji: "🇮🇩" },
  { code: "IR", name: "Iran", emoji: "🇮🇷" },
  { code: "IQ", name: "Iraq", emoji: "🇮🇶" },
  { code: "IE", name: "Ireland", emoji: "🇮🇪" },
  { code: "IL", name: "Israel", emoji: "🇮🇱" },
  { code: "IT", name: "Italy", emoji: "🇮🇹" },
  { code: "JM", name: "Jamaica", emoji: "🇯🇲" },
  { code: "JP", name: "Japan", emoji: "🇯🇵" },
  { code: "JO", name: "Jordan", emoji: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", emoji: "🇰🇿" },
  { code: "KE", name: "Kenya", emoji: "🇰🇪" },
  { code: "KI", name: "Kiribati", emoji: "🇰🇮" },
  { code: "KW", name: "Kuwait", emoji: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", emoji: "🇰🇬" },
  { code: "LA", name: "Laos", emoji: "🇱🇦" },
  { code: "LV", name: "Latvia", emoji: "🇱🇻" },
  { code: "LB", name: "Lebanon", emoji: "🇱🇧" },
  { code: "LS", name: "Lesotho", emoji: "🇱🇸" },
  { code: "LR", name: "Liberia", emoji: "🇱🇷" },
  { code: "LY", name: "Libya", emoji: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", emoji: "🇱🇮" },
  { code: "LT", name: "Lithuania", emoji: "🇱🇹" },
  { code: "LU", name: "Luxembourg", emoji: "🇱🇺" },
  { code: "MG", name: "Madagascar", emoji: "🇲🇬" },
  { code: "MW", name: "Malawi", emoji: "🇲🇼" },
  { code: "MY", name: "Malaysia", emoji: "🇲🇾" },
  { code: "MV", name: "Maldives", emoji: "🇲🇻" },
  { code: "ML", name: "Mali", emoji: "🇲🇱" },
  { code: "MT", name: "Malta", emoji: "🇲🇹" },
  { code: "MH", name: "Marshall Islands", emoji: "🇲🇭" },
  { code: "MR", name: "Mauritania", emoji: "🇲🇷" },
  { code: "MU", name: "Mauritius", emoji: "🇲🇺" },
  { code: "MX", name: "Mexico", emoji: "🇲🇽" },
  { code: "FM", name: "Micronesia", emoji: "🇫🇲" },
  { code: "MD", name: "Moldova", emoji: "🇲🇩" },
  { code: "MC", name: "Monaco", emoji: "🇲🇨" },
  { code: "MN", name: "Mongolia", emoji: "🇲🇳" },
  { code: "ME", name: "Montenegro", emoji: "🇲🇪" },
  { code: "MA", name: "Morocco", emoji: "🇲🇦" },
  { code: "MZ", name: "Mozambique", emoji: "🇲🇿" },
  { code: "MM", name: "Myanmar", emoji: "🇲🇲" },
  { code: "NA", name: "Namibia", emoji: "🇳🇦" },
  { code: "NR", name: "Nauru", emoji: "🇳🇷" },
  { code: "NP", name: "Nepal", emoji: "🇳🇵" },
  { code: "NL", name: "Netherlands", emoji: "🇳🇱" },
  { code: "NZ", name: "New Zealand", emoji: "🇳🇿" },
  { code: "NI", name: "Nicaragua", emoji: "🇳🇮" },
  { code: "NE", name: "Niger", emoji: "🇳🇪" },
  { code: "NG", name: "Nigeria", emoji: "🇳🇬" },
  { code: "NO", name: "Norway", emoji: "🇳🇴" },
  { code: "OM", name: "Oman", emoji: "🇴🇲" },
  { code: "PK", name: "Pakistan", emoji: "🇵🇰" },
  { code: "PW", name: "Palau", emoji: "🇵🇼" },
  { code: "PA", name: "Panama", emoji: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", emoji: "🇵🇬" },
  { code: "PY", name: "Paraguay", emoji: "🇵🇾" },
  { code: "PE", name: "Peru", emoji: "🇵🇪" },
  { code: "PH", name: "Philippines", emoji: "🇵🇭" },
  { code: "PL", name: "Poland", emoji: "🇵🇱" },
  { code: "PT", name: "Portugal", emoji: "🇵🇹" },
  { code: "QA", name: "Qatar", emoji: "🇶🇦" },
  { code: "RO", name: "Romania", emoji: "🇷🇴" },
  { code: "RU", name: "Russia", emoji: "🇷🇺" },
  { code: "RW", name: "Rwanda", emoji: "🇷🇼" },
  { code: "KN", name: "Saint Kitts and Nevis", emoji: "🇰🇳" },
  { code: "LC", name: "Saint Lucia", emoji: "🇱🇨" },
  { code: "VC", name: "Saint Vincent and the Grenadines", emoji: "🇻🇨" },
  { code: "WS", name: "Samoa", emoji: "🇼🇸" },
  { code: "SM", name: "San Marino", emoji: "🇸🇲" },
  { code: "ST", name: "Sao Tome and Principe", emoji: "🇸🇹" },
  { code: "SA", name: "Saudi Arabia", emoji: "🇸🇦" },
  { code: "SN", name: "Senegal", emoji: "🇸🇳" },
  { code: "RS", name: "Serbia", emoji: "🇷🇸" },
  { code: "SC", name: "Seychelles", emoji: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", emoji: "🇸🇱" },
  { code: "SG", name: "Singapore", emoji: "🇸🇬" },
  { code: "SK", name: "Slovakia", emoji: "🇸🇰" },
  { code: "SI", name: "Slovenia", emoji: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", emoji: "🇸🇧" },
  { code: "SO", name: "Somalia", emoji: "🇸🇴" },
  { code: "ZA", name: "South Africa", emoji: "🇿🇦" },
  { code: "SS", name: "South Sudan", emoji: "🇸🇸" },
  { code: "ES", name: "Spain", emoji: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", emoji: "🇱🇰" },
  { code: "SD", name: "Sudan", emoji: "🇸🇩" },
  { code: "SR", name: "Suriname", emoji: "🇸🇷" },
  { code: "SE", name: "Sweden", emoji: "🇸🇪" },
  { code: "CH", name: "Switzerland", emoji: "🇨🇭" },
  { code: "SY", name: "Syria", emoji: "🇸🇾" },
  { code: "TW", name: "Taiwan", emoji: "🇹🇼" },
  { code: "TJ", name: "Tajikistan", emoji: "🇹🇯" },
  { code: "TZ", name: "Tanzania", emoji: "🇹🇿" },
  { code: "TH", name: "Thailand", emoji: "🇹🇭" },
  { code: "TL", name: "Timor-Leste", emoji: "🇹🇱" },
  { code: "TG", name: "Togo", emoji: "🇹🇬" },
  { code: "TO", name: "Tonga", emoji: "🇹🇴" },
  { code: "TT", name: "Trinidad and Tobago", emoji: "🇹🇹" },
  { code: "TN", name: "Tunisia", emoji: "🇹🇳" },
  { code: "TR", name: "Turkey", emoji: "🇹🇷" },
  { code: "TM", name: "Turkmenistan", emoji: "🇹🇲" },
  { code: "TV", name: "Tuvalu", emoji: "🇹🇻" },
  { code: "UG", name: "Uganda", emoji: "🇺🇬" },
  { code: "UA", name: "Ukraine", emoji: "🇺🇦" },
  { code: "AE", name: "United Arab Emirates", emoji: "🇦🇪" },
  { code: "GB", name: "United Kingdom", emoji: "🇬🇧" },
  { code: "US", name: "United States", emoji: "🇺🇸" },
  { code: "UY", name: "Uruguay", emoji: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", emoji: "🇺🇿" },
  { code: "VU", name: "Vanuatu", emoji: "🇻🇺" },
  { code: "VE", name: "Venezuela", emoji: "🇻🇪" },
  { code: "VN", name: "Vietnam", emoji: "🇻🇳" },
  { code: "YE", name: "Yemen", emoji: "🇾🇪" },
  { code: "ZM", name: "Zambia", emoji: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", emoji: "🇿🇼" },
];

export const STATES_BY_COUNTRY: Record<string, Region[]> = {
  US: [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" }, { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" }, { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" }, { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" }, { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" }, { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" }, { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" }, { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" }, { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" }, { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" }, { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" }, { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" }, { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" }, { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
  ],
  CA: [
    { code: "AB", name: "Alberta" }, { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" }, { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" }, { code: "NS", name: "Nova Scotia" },
    { code: "NT", name: "Northwest Territories" }, { code: "NU", name: "Nunavut" },
    { code: "ON", name: "Ontario" }, { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" }, { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT",  name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA",  name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA",  name: "Western Australia" },
  ],
  GB: [
    { code: "ENG", name: "England" }, { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" }, { code: "NIR", name: "Northern Ireland" },
  ],
  IN: [
    { code: "AN", name: "Andaman and Nicobar Islands" }, { code: "AP", name: "Andhra Pradesh" },
    { code: "AR", name: "Arunachal Pradesh" }, { code: "AS", name: "Assam" },
    { code: "BR", name: "Bihar" }, { code: "CH", name: "Chandigarh" },
    { code: "CT", name: "Chhattisgarh" }, { code: "DH", name: "Dadra and Nagar Haveli and Daman and Diu" },
    { code: "DL", name: "Delhi" }, { code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" }, { code: "HR", name: "Haryana" },
    { code: "HP", name: "Himachal Pradesh" }, { code: "JK", name: "Jammu and Kashmir" },
    { code: "JH", name: "Jharkhand" }, { code: "KA", name: "Karnataka" },
    { code: "KL", name: "Kerala" }, { code: "LA", name: "Ladakh" },
    { code: "LD", name: "Lakshadweep" }, { code: "MP", name: "Madhya Pradesh" },
    { code: "MH", name: "Maharashtra" }, { code: "MN", name: "Manipur" },
    { code: "ML", name: "Meghalaya" }, { code: "MZ", name: "Mizoram" },
    { code: "NL", name: "Nagaland" }, { code: "OR", name: "Odisha" },
    { code: "PY", name: "Puducherry" }, { code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" }, { code: "SK", name: "Sikkim" },
    { code: "TN", name: "Tamil Nadu" }, { code: "TG", name: "Telangana" },
    { code: "TR", name: "Tripura" }, { code: "UP", name: "Uttar Pradesh" },
    { code: "UT", name: "Uttarakhand" }, { code: "WB", name: "West Bengal" },
  ],
  DE: [
    { code: "BB", name: "Brandenburg" }, { code: "BE", name: "Berlin" },
    { code: "BW", name: "Baden-Württemberg" }, { code: "BY", name: "Bavaria" },
    { code: "HB", name: "Bremen" }, { code: "HE", name: "Hesse" },
    { code: "HH", name: "Hamburg" }, { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Lower Saxony" }, { code: "NW", name: "North Rhine-Westphalia" },
    { code: "RP", name: "Rhineland-Palatinate" }, { code: "SH", name: "Schleswig-Holstein" },
    { code: "SL", name: "Saarland" }, { code: "SN", name: "Saxony" },
    { code: "ST", name: "Saxony-Anhalt" }, { code: "TH", name: "Thuringia" },
  ],
  FR: [
    { code: "ARA", name: "Auvergne-Rhône-Alpes" }, { code: "BFC", name: "Bourgogne-Franche-Comté" },
    { code: "BRE", name: "Brittany" }, { code: "CVL", name: "Centre-Val de Loire" },
    { code: "COR", name: "Corsica" }, { code: "GES", name: "Grand Est" },
    { code: "HDF", name: "Hauts-de-France" }, { code: "IDF", name: "Île-de-France" },
    { code: "NOR", name: "Normandy" }, { code: "NAQ", name: "Nouvelle-Aquitaine" },
    { code: "OCC", name: "Occitanie" }, { code: "PDL", name: "Pays de la Loire" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  ],
  BR: [
    { code: "AC", name: "Acre" }, { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" }, { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" }, { code: "CE", name: "Ceará" },
    { code: "DF", name: "Distrito Federal" }, { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" }, { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" }, { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" }, { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" }, { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" }, { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" }, { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" }, { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" }, { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" }, { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes" }, { code: "BCN", name: "Baja California" },
    { code: "BCS", name: "Baja California Sur" }, { code: "CAM", name: "Campeche" },
    { code: "CHP", name: "Chiapas" }, { code: "CHH", name: "Chihuahua" },
    { code: "CMX", name: "Mexico City" }, { code: "COA", name: "Coahuila" },
    { code: "COL", name: "Colima" }, { code: "DUR", name: "Durango" },
    { code: "GUA", name: "Guanajuato" }, { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" }, { code: "JAL", name: "Jalisco" },
    { code: "MEX", name: "México" }, { code: "MIC", name: "Michoacán" },
    { code: "MOR", name: "Morelos" }, { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" }, { code: "OAX", name: "Oaxaca" },
    { code: "PUE", name: "Puebla" }, { code: "QUE", name: "Querétaro" },
    { code: "ROO", name: "Quintana Roo" }, { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" }, { code: "SON", name: "Sonora" },
    { code: "TAB", name: "Tabasco" }, { code: "TAM", name: "Tamaulipas" },
    { code: "TLA", name: "Tlaxcala" }, { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" }, { code: "ZAC", name: "Zacatecas" },
  ],
  AR: [
    { code: "B", name: "Buenos Aires Province" }, { code: "C", name: "Buenos Aires (City)" },
    { code: "K", name: "Catamarca" }, { code: "H", name: "Chaco" },
    { code: "U", name: "Chubut" }, { code: "X", name: "Córdoba" },
    { code: "W", name: "Corrientes" }, { code: "E", name: "Entre Ríos" },
    { code: "P", name: "Formosa" }, { code: "Y", name: "Jujuy" },
    { code: "L", name: "La Pampa" }, { code: "F", name: "La Rioja" },
    { code: "M", name: "Mendoza" }, { code: "N", name: "Misiones" },
    { code: "Q", name: "Neuquén" }, { code: "R", name: "Río Negro" },
    { code: "A", name: "Salta" }, { code: "J", name: "San Juan" },
    { code: "D", name: "San Luis" }, { code: "Z", name: "Santa Cruz" },
    { code: "S", name: "Santa Fe" }, { code: "G", name: "Santiago del Estero" },
    { code: "V", name: "Tierra del Fuego" }, { code: "T", name: "Tucumán" },
  ],
  ZA: [
    { code: "EC", name: "Eastern Cape" }, { code: "FS", name: "Free State" },
    { code: "GP", name: "Gauteng" }, { code: "KZN", name: "KwaZulu-Natal" },
    { code: "LP", name: "Limpopo" }, { code: "MP", name: "Mpumalanga" },
    { code: "NC", name: "Northern Cape" }, { code: "NW", name: "North West" },
    { code: "WC", name: "Western Cape" },
  ],
  NG: [
    { code: "AB", name: "Abia" }, { code: "AD", name: "Adamawa" },
    { code: "AK", name: "Akwa Ibom" }, { code: "AN", name: "Anambra" },
    { code: "BA", name: "Bauchi" }, { code: "BY", name: "Bayelsa" },
    { code: "BE", name: "Benue" }, { code: "BO", name: "Borno" },
    { code: "CR", name: "Cross River" }, { code: "DE", name: "Delta" },
    { code: "EB", name: "Ebonyi" }, { code: "ED", name: "Edo" },
    { code: "EK", name: "Ekiti" }, { code: "EN", name: "Enugu" },
    { code: "FC", name: "Federal Capital Territory" }, { code: "GO", name: "Gombe" },
    { code: "IM", name: "Imo" }, { code: "JI", name: "Jigawa" },
    { code: "KD", name: "Kaduna" }, { code: "KN", name: "Kano" },
    { code: "KT", name: "Katsina" }, { code: "KE", name: "Kebbi" },
    { code: "KO", name: "Kogi" }, { code: "KW", name: "Kwara" },
    { code: "LA", name: "Lagos" }, { code: "NA", name: "Nasarawa" },
    { code: "NI", name: "Niger" }, { code: "OG", name: "Ogun" },
    { code: "ON", name: "Ondo" }, { code: "OS", name: "Osun" },
    { code: "OY", name: "Oyo" }, { code: "PL", name: "Plateau" },
    { code: "RI", name: "Rivers" }, { code: "SO", name: "Sokoto" },
    { code: "TA", name: "Taraba" }, { code: "YO", name: "Yobe" },
    { code: "ZA", name: "Zamfara" },
  ],
  PK: [
    { code: "BA", name: "Balochistan" }, { code: "GB", name: "Gilgit-Baltistan" },
    { code: "IS", name: "Islamabad Capital Territory" }, { code: "AK", name: "Azad Kashmir" },
    { code: "KP", name: "Khyber Pakhtunkhwa" }, { code: "PB", name: "Punjab" },
    { code: "SD", name: "Sindh" },
  ],
  MY: [
    { code: "JHR", name: "Johor" }, { code: "KDH", name: "Kedah" },
    { code: "KTN", name: "Kelantan" }, { code: "KUL", name: "Kuala Lumpur" },
    { code: "LBN", name: "Labuan" }, { code: "MLK", name: "Melaka" },
    { code: "NSN", name: "Negeri Sembilan" }, { code: "PHG", name: "Pahang" },
    { code: "PNG", name: "Penang" }, { code: "PRK", name: "Perak" },
    { code: "PLS", name: "Perlis" }, { code: "PJY", name: "Putrajaya" },
    { code: "SBH", name: "Sabah" }, { code: "SWK", name: "Sarawak" },
    { code: "SGR", name: "Selangor" }, { code: "TRG", name: "Terengganu" },
  ],
  PH: [
    { code: "ABR", name: "Abra" }, { code: "AGN", name: "Agusan del Norte" },
    { code: "AGS", name: "Agusan del Sur" }, { code: "AKL", name: "Aklan" },
    { code: "ALB", name: "Albay" }, { code: "ANT", name: "Antique" },
    { code: "APA", name: "Apayao" }, { code: "AUR", name: "Aurora" },
    { code: "BAS", name: "Basilan" }, { code: "BAN", name: "Bataan" },
    { code: "BTN", name: "Batanes" }, { code: "BTG", name: "Batangas" },
    { code: "BEN", name: "Benguet" }, { code: "BIL", name: "Biliran" },
    { code: "BOH", name: "Bohol" }, { code: "BUK", name: "Bukidnon" },
    { code: "BUL", name: "Bulacan" }, { code: "CAG", name: "Cagayan" },
    { code: "CAN", name: "Camarines Norte" }, { code: "CAS", name: "Camarines Sur" },
    { code: "CAM", name: "Camiguin" }, { code: "CAP", name: "Capiz" },
    { code: "CAT", name: "Catanduanes" }, { code: "CAV", name: "Cavite" },
    { code: "CEB", name: "Cebu" }, { code: "NCR", name: "Metro Manila" },
  ],
  ID: [
    { code: "AC", name: "Aceh" }, { code: "BA", name: "Bali" },
    { code: "BB", name: "Bangka Belitung Islands" }, { code: "BT", name: "Banten" },
    { code: "BE", name: "Bengkulu" }, { code: "JT", name: "Central Java" },
    { code: "KT", name: "Central Kalimantan" }, { code: "ST", name: "Central Sulawesi" },
    { code: "JI", name: "East Java" }, { code: "KI", name: "East Kalimantan" },
    { code: "NT", name: "East Nusa Tenggara" }, { code: "GO", name: "Gorontalo" },
    { code: "JK", name: "Jakarta" }, { code: "JA", name: "Jambi" },
    { code: "LA", name: "Lampung" }, { code: "MA", name: "Maluku" },
    { code: "KU", name: "North Kalimantan" }, { code: "MU", name: "North Maluku" },
    { code: "SA", name: "North Sulawesi" }, { code: "SU", name: "North Sumatra" },
    { code: "PA", name: "Papua" }, { code: "PB", name: "West Papua" },
    { code: "RI", name: "Riau" }, { code: "KR", name: "Riau Islands" },
    { code: "SG", name: "Southeast Sulawesi" }, { code: "SS", name: "South Sumatra" },
    { code: "SR", name: "South Sulawesi" }, { code: "KS", name: "South Kalimantan" },
    { code: "NB", name: "West Nusa Tenggara" }, { code: "KB", name: "West Kalimantan" },
    { code: "JB", name: "West Java" }, { code: "SB", name: "West Sumatra" },
    { code: "YO", name: "Yogyakarta" },
  ],
  AE: [
    { code: "AZ", name: "Abu Dhabi" }, { code: "AJ", name: "Ajman" },
    { code: "DU", name: "Dubai" }, { code: "FU", name: "Fujairah" },
    { code: "RK", name: "Ras Al Khaimah" }, { code: "SH", name: "Sharjah" },
    { code: "UQ", name: "Umm Al Quwain" },
  ],
  SA: [
    { code: "01", name: "Riyadh" }, { code: "02", name: "Makkah" },
    { code: "03", name: "Madinah" }, { code: "04", name: "Eastern Province" },
    { code: "05", name: "Al-Qassim" }, { code: "06", name: "Hail" },
    { code: "07", name: "Tabuk" }, { code: "08", name: "Northern Borders" },
    { code: "09", name: "Jizan" }, { code: "10", name: "Najran" },
    { code: "11", name: "Al-Bahah" }, { code: "12", name: "Al-Jawf" },
    { code: "14", name: "Asir" },
  ],
  IT: [
    { code: "65", name: "Abruzzo" }, { code: "77", name: "Basilicata" },
    { code: "78", name: "Calabria" }, { code: "72", name: "Campania" },
    { code: "45", name: "Emilia-Romagna" }, { code: "36", name: "Friuli-Venezia Giulia" },
    { code: "62", name: "Lazio" }, { code: "42", name: "Liguria" },
    { code: "25", name: "Lombardy" }, { code: "57", name: "Marche" },
    { code: "67", name: "Molise" }, { code: "21", name: "Piedmont" },
    { code: "75", name: "Apulia" }, { code: "88", name: "Sardinia" },
    { code: "82", name: "Sicily" }, { code: "52", name: "Tuscany" },
    { code: "32", name: "Trentino-Alto Adige" }, { code: "55", name: "Umbria" },
    { code: "23", name: "Aosta Valley" }, { code: "34", name: "Veneto" },
  ],
  ES: [
    { code: "AN", name: "Andalusia" }, { code: "AR", name: "Aragon" },
    { code: "AS", name: "Asturias" }, { code: "CN", name: "Canary Islands" },
    { code: "CB", name: "Cantabria" }, { code: "CM", name: "Castilla–La Mancha" },
    { code: "CL", name: "Castile and León" }, { code: "CT", name: "Catalonia" },
    { code: "CE", name: "Ceuta" }, { code: "EX", name: "Extremadura" },
    { code: "GA", name: "Galicia" }, { code: "IB", name: "Balearic Islands" },
    { code: "RI", name: "La Rioja" }, { code: "MD", name: "Community of Madrid" },
    { code: "ME", name: "Melilla" }, { code: "MC", name: "Region of Murcia" },
    { code: "NC", name: "Navarre" }, { code: "PV", name: "Basque Country" },
    { code: "VC", name: "Valencian Community" },
  ],
  JP: [
    { code: "01", name: "Hokkaido" }, { code: "02", name: "Aomori" },
    { code: "03", name: "Iwate" }, { code: "04", name: "Miyagi" },
    { code: "05", name: "Akita" }, { code: "06", name: "Yamagata" },
    { code: "07", name: "Fukushima" }, { code: "08", name: "Ibaraki" },
    { code: "09", name: "Tochigi" }, { code: "10", name: "Gunma" },
    { code: "11", name: "Saitama" }, { code: "12", name: "Chiba" },
    { code: "13", name: "Tokyo" }, { code: "14", name: "Kanagawa" },
    { code: "15", name: "Niigata" }, { code: "16", name: "Toyama" },
    { code: "17", name: "Ishikawa" }, { code: "18", name: "Fukui" },
    { code: "19", name: "Yamanashi" }, { code: "20", name: "Nagano" },
    { code: "21", name: "Gifu" }, { code: "22", name: "Shizuoka" },
    { code: "23", name: "Aichi" }, { code: "24", name: "Mie" },
    { code: "25", name: "Shiga" }, { code: "26", name: "Kyoto" },
    { code: "27", name: "Osaka" }, { code: "28", name: "Hyogo" },
    { code: "29", name: "Nara" }, { code: "30", name: "Wakayama" },
    { code: "31", name: "Tottori" }, { code: "32", name: "Shimane" },
    { code: "33", name: "Okayama" }, { code: "34", name: "Hiroshima" },
    { code: "35", name: "Yamaguchi" }, { code: "36", name: "Tokushima" },
    { code: "37", name: "Kagawa" }, { code: "38", name: "Ehime" },
    { code: "39", name: "Kochi" }, { code: "40", name: "Fukuoka" },
    { code: "41", name: "Saga" }, { code: "42", name: "Nagasaki" },
    { code: "43", name: "Kumamoto" }, { code: "44", name: "Oita" },
    { code: "45", name: "Miyazaki" }, { code: "46", name: "Kagoshima" },
    { code: "47", name: "Okinawa" },
  ],
  CN: [
    { code: "AH", name: "Anhui" }, { code: "BJ", name: "Beijing" },
    { code: "CQ", name: "Chongqing" }, { code: "FJ", name: "Fujian" },
    { code: "GS", name: "Gansu" }, { code: "GD", name: "Guangdong" },
    { code: "GX", name: "Guangxi" }, { code: "GZ", name: "Guizhou" },
    { code: "HI", name: "Hainan" }, { code: "HE", name: "Hebei" },
    { code: "HL", name: "Heilongjiang" }, { code: "HA", name: "Henan" },
    { code: "HB", name: "Hubei" }, { code: "HN", name: "Hunan" },
    { code: "JS", name: "Jiangsu" }, { code: "JX", name: "Jiangxi" },
    { code: "JL", name: "Jilin" }, { code: "LN", name: "Liaoning" },
    { code: "NM", name: "Inner Mongolia" }, { code: "NX", name: "Ningxia" },
    { code: "QH", name: "Qinghai" }, { code: "SN", name: "Shaanxi" },
    { code: "SD", name: "Shandong" }, { code: "SH", name: "Shanghai" },
    { code: "SX", name: "Shanxi" }, { code: "SC", name: "Sichuan" },
    { code: "TJ", name: "Tianjin" }, { code: "XJ", name: "Xinjiang" },
    { code: "XZ", name: "Tibet" }, { code: "YN", name: "Yunnan" },
    { code: "ZJ", name: "Zhejiang" },
  ],
  RU: [
    { code: "MOW", name: "Moscow" }, { code: "SPE", name: "Saint Petersburg" },
    { code: "NOV", name: "Novosibirsk Oblast" }, { code: "SVE", name: "Sverdlovsk Oblast" },
    { code: "KRA", name: "Krasnodar Krai" }, { code: "NI", name: "Nizhny Novgorod Oblast" },
    { code: "TAT", name: "Republic of Tatarstan" }, { code: "CHE", name: "Chelyabinsk Oblast" },
    { code: "SAM", name: "Samara Oblast" }, { code: "ROS", name: "Rostov Oblast" },
    { code: "UFА", name: "Republic of Bashkortostan" }, { code: "KEM", name: "Kemerovo Oblast" },
    { code: "PER", name: "Perm Krai" }, { code: "VOR", name: "Voronezh Oblast" },
    { code: "KRS", name: "Krasnoyarsk Krai" },
  ],
  KE: [
    { code: "01", name: "Mombasa" }, { code: "02", name: "Kwale" },
    { code: "03", name: "Kilifi" }, { code: "04", name: "Tana River" },
    { code: "05", name: "Lamu" }, { code: "06", name: "Taita-Taveta" },
    { code: "07", name: "Garissa" }, { code: "08", name: "Wajir" },
    { code: "09", name: "Mandera" }, { code: "10", name: "Marsabit" },
    { code: "11", name: "Isiolo" }, { code: "12", name: "Meru" },
    { code: "13", name: "Tharaka-Nithi" }, { code: "14", name: "Embu" },
    { code: "15", name: "Kitui" }, { code: "16", name: "Machakos" },
    { code: "17", name: "Makueni" }, { code: "18", name: "Nyandarua" },
    { code: "19", name: "Nyeri" }, { code: "20", name: "Kirinyaga" },
    { code: "21", name: "Murang'a" }, { code: "22", name: "Kiambu" },
    { code: "23", name: "Turkana" }, { code: "24", name: "West Pokot" },
    { code: "25", name: "Samburu" }, { code: "26", name: "Trans Nzoia" },
    { code: "27", name: "Uasin Gishu" }, { code: "28", name: "Elgeyo-Marakwet" },
    { code: "29", name: "Nandi" }, { code: "30", name: "Baringo" },
    { code: "31", name: "Laikipia" }, { code: "32", name: "Nakuru" },
    { code: "33", name: "Narok" }, { code: "34", name: "Kajiado" },
    { code: "35", name: "Kericho" }, { code: "36", name: "Bomet" },
    { code: "37", name: "Kakamega" }, { code: "38", name: "Vihiga" },
    { code: "39", name: "Bungoma" }, { code: "40", name: "Busia" },
    { code: "41", name: "Siaya" }, { code: "42", name: "Kisumu" },
    { code: "43", name: "Homa Bay" }, { code: "44", name: "Migori" },
    { code: "45", name: "Kisii" }, { code: "46", name: "Nyamira" },
    { code: "47", name: "Nairobi" },
  ],
  NZ: [
    { code: "AUK", name: "Auckland" }, { code: "BOP", name: "Bay of Plenty" },
    { code: "CAN", name: "Canterbury" }, { code: "GIS", name: "Gisborne" },
    { code: "HKB", name: "Hawke's Bay" }, { code: "MBH", name: "Marlborough" },
    { code: "MWT", name: "Manawatu-Whanganui" }, { code: "NSN", name: "Nelson" },
    { code: "NTL", name: "Northland" }, { code: "OTA", name: "Otago" },
    { code: "STL", name: "Southland" }, { code: "TAS", name: "Tasman" },
    { code: "TKI", name: "Taranaki" }, { code: "WGN", name: "Wellington" },
    { code: "WKO", name: "Waikato" }, { code: "WTC", name: "West Coast" },
  ],
  IE: [
    { code: "CW", name: "Carlow" }, { code: "CN", name: "Cavan" },
    { code: "CE", name: "Clare" }, { code: "CO", name: "Cork" },
    { code: "DL", name: "Donegal" }, { code: "D", name: "Dublin" },
    { code: "G", name: "Galway" }, { code: "KY", name: "Kerry" },
    { code: "KE", name: "Kildare" }, { code: "KK", name: "Kilkenny" },
    { code: "LS", name: "Laois" }, { code: "LM", name: "Leitrim" },
    { code: "LK", name: "Limerick" }, { code: "LD", name: "Longford" },
    { code: "LH", name: "Louth" }, { code: "MO", name: "Mayo" },
    { code: "MH", name: "Meath" }, { code: "MN", name: "Monaghan" },
    { code: "OY", name: "Offaly" }, { code: "RN", name: "Roscommon" },
    { code: "SO", name: "Sligo" }, { code: "TA", name: "Tipperary" },
    { code: "WD", name: "Waterford" }, { code: "WH", name: "Westmeath" },
    { code: "WX", name: "Wexford" }, { code: "WW", name: "Wicklow" },
  ],
};

export function getStates(countryCode: string): Region[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}
